swagger: '2.0'
schemes:
  - https
host: holaMundo.insomewhere.igrupobbva
info:
  contact:
    email: carmen.jimenez.cabezas@bbva.com
    name: Carmen J. Cabezas
    url: 'https://www.linkedin.com/in/carmenjimenezcabezas/'
  description: >-
    Hola mundo
    https://github.com/mcjimenez/presentations/tree/gh-pages/openapibp<urlDoc>
  title: holaMundo
  version: 0.0.1
basePath: /
x-implementation-middleware:
  - checkPremium
parameters:
  person:
    name: person
    description: Name of the person that will be included on the greeting.
    in: path
    required: true
    type: string
definitions:
  regards:
    description: >-
      A Dictionary of `greeting`, where the keys are the language in which the greeting is
    type: object
    additionalProperties:
      $ref: '#/definitions/greeting'
  greeting:
    description: The customized greeting that is generated
    type: string
paths:
  '/v1/regards/{person}':
    get:
      summary: Returns a greeting to the given person
      description: >-
        Returns a greeting that is personalized to the given person.
        If the person is a premium user,
        then the greeting will be returned in several languages.
      operationId: getRegards
      parameters:
        - $ref: '#/parameters/person'
      responses:
        '200':
          description: >-
            The request was succeed.
          schema:
            $ref: '#/definitions/regards'
        '400':
          description: The request will not succeed.